### ISSUE TITLE
NoMethodError: undefined method `call_flex'

### ISSUE THREAD

**Issue by smoothdvd** [rubyamf/rocketamf#13]
When I type these code in irb:

``` ruby
req = RocketAMF::Envelope.new :amf_version => 3
req.call_flex 'Controller.action', "arg_1", ["args", "args"]
```

it reports:

``` ruby
NoMethodError: undefined method `call_flex' for #<RocketAMF::Envelope:0x007fa464376aa8>
```

**Comment by warhammerkid** [comment]
The official RocketAMF gem (version 0.2.1) does not support `call_flex`, so you will have to use Bundler to get RocketAMF from git if you want to use it.

**Comment by smoothdvd** [comment]
@warhammerkid Thanks! I will try.
